//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorias
    {
        public categorias()
        {
            this.productos = new HashSet<productos>();
        }
    
        public int cod_categoria { get; set; }
        public string categoria { get; set; }
        public Nullable<int> cod_tipo_producto { get; set; }
    
        public virtual tipos_de_productos tipos_de_productos { get; set; }
        public virtual ICollection<productos> productos { get; set; }
    }
}
