//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public permisos()
        {
            this.roles = new HashSet<roles>();
        }
    
        public int cod_permiso { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> permiso_activado { get; set; }
    
        public virtual ICollection<roles> roles { get; set; }
    }
}
