//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public productos()
        {
            this.productos_y_ubicaciones = new HashSet<productos_y_ubicaciones>();
            this.ventas_de_productos = new HashSet<ventas_de_productos>();
        }
    
        public int cod_producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> cod_categoria { get; set; }
        public Nullable<int> cod_oferta { get; set; }
        public byte[] imagen_producto { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual ofertas ofertas { get; set; }
        public virtual ICollection<productos_y_ubicaciones> productos_y_ubicaciones { get; set; }
        public virtual ICollection<ventas_de_productos> ventas_de_productos { get; set; }
    }
}
