//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_y_ubicaciones
    {
        public int cod_producto { get; set; }
        public string cod_ubicacion { get; set; }
        public Nullable<int> cantidad_en_stock { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual ubicaciones ubicaciones { get; set; }
    }
}
