//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.usuarios = new HashSet<usuarios>();
            this.permisos = new HashSet<permisos>();
        }
    
        public int cod_rol { get; set; }
        public string tipo_rol { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
        public virtual ICollection<permisos> permisos { get; set; }
    }
}
