//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_de_productos
    {
        public tipos_de_productos()
        {
            this.categorias = new HashSet<categorias>();
        }
    
        public int cod_tipo_producto { get; set; }
        public string tipo_de_producto { get; set; }
    
        public virtual ICollection<categorias> categorias { get; set; }
    }
}
