//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicaciones
    {
        public ubicaciones()
        {
            this.productos_y_ubicaciones = new HashSet<productos_y_ubicaciones>();
            this.ubicaciones1 = new HashSet<ubicaciones>();
            this.ubicaciones2 = new HashSet<ubicaciones>();
        }
    
        public string cod_ubicacion { get; set; }
        public string descripcion_ubicacion { get; set; }
        public Nullable<bool> tipo_almacen { get; set; }
    
        public virtual ICollection<productos_y_ubicaciones> productos_y_ubicaciones { get; set; }
        public virtual ICollection<ubicaciones> ubicaciones1 { get; set; }
        public virtual ICollection<ubicaciones> ubicaciones2 { get; set; }
    }
}
