//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using proyecto.tpv.agustin.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ventas : MVBase
    {
        public ventas()
        {
            this.ventas_de_productos = new HashSet<ventas_de_productos>();
        }
    
        public int cod_venta { get; set; }
        public int cod_usuario { get; set; }
        public string mensaje { get; set; }
        [Required]
        public Nullable<System.DateTime> fecha { get; set; }
        //[Required]
        public Nullable<double> total { get; set; }
        public Nullable<double> iva { get; set; }
        public int cod_cliente { get; set; }
        //[Required]
        public Nullable<double> total_mas_iva { get; set; }

        [Required]
        public virtual clientes clientes { get; set; }
        [Required]
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<ventas_de_productos> ventas_de_productos { get; set; }
    }
}
