//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.tpv.agustin.Modelo
{
    using proyecto.tpv.agustin.MVVM;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ventas_de_productos : MVBase
    {
        public int cod_venta { get; set; }
        public int cod_producto { get; set; }
        //[Required]
        public Nullable<int> cantidad_vendida { get; set; }
        //[Required]
        public Nullable<double> precio_total_unidades { get; set; }
        //[Required]
        public virtual productos productos { get; set; }
        //[Required]
        public virtual ventas ventas { get; set; }
    }
}
